name: Deploy HAProxy for Patroni Cluster

on:
  workflow_dispatch:

jobs:
  provision-haproxy:
    uses: KoraMaple/nante-reusable-workflow/.github/workflows/reusable-provision.yml@develop
    with:
      app_name: patroni-ha-lb
      resource_type: lxc
      vlan_tag: "20"
      vm_target_ip: "<INTERNAL_IP_VLAN20>"
      cpu_cores: "2"
      ram_mb: "2048"
      disk_gb: "15G"
      ansible_roles: haproxy
      # Pass Patroni backend IPs - replace with your actual Patroni node IPs
      # Format: name:ip,name:ip,name:ip
      ansible_extra_vars: patroni_backends=patroni-ha-node1:<INTERNAL_IP_VLAN20>,patroni-ha-node2:<INTERNAL_IP_VLAN20>,patroni-ha-node3:<INTERNAL_IP_VLAN20>
      lxc_unprivileged: true
      skip_octopus: true
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      DOPPLER_TARGET_PROJECT: ${{ secrets.DOPPLER_TARGET_PROJECT }}
      DOPPLER_TARGET_CONFIG: ${{ secrets.DOPPLER_TARGET_CONFIG }}
      GH_PAT: ${{ secrets.GH_PAT }}
