name: Deploy HAProxy for Patroni Cluster

on:
  workflow_dispatch:

jobs:
  provision-haproxy:
    uses: KoraMaple/nante-reusable-workflow/.github/workflows/reusable-provision.yml@develop
    with:
      app_name: patroni-ha-lb
      resource_type: lxc
      vlan_tag: "20"
      vm_target_ip: "192.168.20.63"
      cpu_cores: "2"
      ram_mb: "2048"
      disk_gb: "15G"
      ansible_roles: haproxy
      # Pass Patroni backend IPs - replace with your actual Patroni node IPs
      ansible_extra_vars: patroni_backends=[{'name':'patroni-ha-node1','ip':'192.168.20.70'},{'name':'patroni-ha-node2','ip':'192.168.20.71'},{'name':'patroni-ha-node3','ip':'192.168.20.72'}]
      lxc_unprivileged: true
      skip_octopus: true
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      DOPPLER_TARGET_PROJECT: ${{ secrets.DOPPLER_TARGET_PROJECT }}
      DOPPLER_TARGET_CONFIG: ${{ secrets.DOPPLER_TARGET_CONFIG }}
      GH_PAT: ${{ secrets.GH_PAT }}
