name: Provision LXC Container Example

on:
  workflow_dispatch:
    inputs:
      container_name:
        description: 'Container name'
        required: true
        default: 'web-app'

jobs:
  provision-lxc:
    uses: ./.github/workflows/reusable-provision.yml
    with:
      # Resource type
      resource_type: lxc
      
      # Container configuration
      app_name: ${{ inputs.container_name }}
      environment: 'dev'
      vm_target_ip: 192.168.20.100
      
      # Resources (LXC uses less than VMs)
      cpu_cores: '2'
      ram_mb: '2048'
      disk_gb: '8'
      
      # LXC-specific
      lxc_template: 'local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
      lxc_unprivileged: true  # Recommended for security
      lxc_nesting: false  # Set to true for Docker support
      
      # Infrastructure
      vlan_tag: '20'
      proxmox_node: 'pmx'
      proxmox_storage: 'zfs-vm'
      
      # Octopus Deploy
      octopus_environment: 'Development'
      octopus_roles: 'web-server,nodejs'
      
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      DOPPLER_TARGET_PROJECT: ${{ secrets.DOPPLER_TARGET_PROJECT }}
      DOPPLER_TARGET_CONFIG: ${{ secrets.DOPPLER_TARGET_CONFIG }}
      GH_PAT: ${{ secrets.GH_PAT }}
