name: Go Application CI Example

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application name'
        required: true
        default: 'my-go-app'
      run_sonar_scan:
        description: 'Run SonarQube scan'
        type: boolean
        default: true

jobs:
  ci:
    uses: KoraMaple/nante-reusable-workflow/.github/workflows/ci-build.yml@main
    with:
      app_name: ${{ inputs.app_name || 'my-go-app' }}
      language: "go"
      language_version: "1.22"
      build_tool: "make"
      run_tests: true
      run_sonar_scan: ${{ inputs.run_sonar_scan || true }}
      skip_nexus_upload: false
    secrets: inherit
