# Example: Provision VM with Octopus Deploy Integration
# ⚠️ Replace placeholder values with your actual configuration

name: Provision VM with Octopus Deploy

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application name'
        required: true
        default: 'nginx'
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - Development
          - Staging
          - Production

jobs:
  provision:
    uses: KoraMaple/nante-reusable-workflow/.github/workflows/reusable-provision.yml@main
    with:
      app_name: ${{ inputs.app_name }}
      vlan_tag: "20"
      vm_target_ip: "<INTERNAL_IP_VLAN20>"  # Replace with your IP, e.g., <INTERNAL_IP_VLAN20>
      cpu_cores: "2"
      ram_mb: "4096"
      disk_gb: "20G"
      # runner_type defaults to "github-hosted" - use "self-hosted" only in private repos
      # Octopus Deploy configuration
      octopus_environment: ${{ inputs.environment }}
      octopus_roles: "web-server,${{ inputs.app_name }}"
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      DOPPLER_TARGET_PROJECT: ${{ secrets.DOPPLER_TARGET_PROJECT }}
      DOPPLER_TARGET_CONFIG: ${{ secrets.DOPPLER_TARGET_CONFIG }}
      GH_PAT: ${{ secrets.GH_PAT }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_CLIENT_SECRET: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
